version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_Fast_API
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15.1-alpine
    container_name: db_app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  tests:
    build:
      context: .
      dockerfile: Dockerfile_test
    container_name: tests
    depends_on:
      - db
    env_file:
      - .env


volumes:
  postgres_data:
